### ISSUE TITLE
Function println not matched when using ArduinoCore-samd core

### ISSUE THREAD

**Issue by enekochan** [arduino/arduino-pro-ide#278]
**Describe the bug**
Using the [ArduinoCore-samd](https://github.com/arduino/ArduinoCore-samd) `println` function in `Serial` is highligthed as "No matching member function for call to '`println`'" even if it is shown in code completition and the sketch is built without problems:

```
No matching member function for call to 'println'

/Users/username/Library/Arduino15/packages/arduino/hardware/samd/1.8.6/cores/arduino/Print.h:78:12:
note: candidate function not viable: no known conversion from 'Uart' to 'Print' for object argument
```

**To Reproduce**
1. Install ArduinoCore-samd.
2. Create a simple sketch and write a `Serial.println("...");` statement
3. See error

**Expected behavior**
Call to `println` be correctly recognized as belonging to `Serial`.

**Screenshots**
![Screenshot 2020-06-20 at 23 13 13](https://user-images.githubusercontent.com/1836845/85211742-6c0e8a00-b34c-11ea-8b6a-16890e7f59d4.png)

**Desktop:**
 - OS: macOS 10.15.5
 - Version: Arduino Pro 0.0.6 (0.0.6.20200409.2)
 - ArduinoCore-samd 1.8.6

**Comment by ubidefeo** [comment]
@enekochan 
This should be resolved, can you try the 0.1.4?
![Screenshot 2021-02-18 at 18 04 43](https://user-images.githubusercontent.com/1894487/108393307-cc273a00-7213-11eb-839c-2ba6ef9df7a1.png)

**Comment by enekochan** [comment]
Yes it works fine :)

**Comment by enekochan** [comment]
Sorry no, still not working.

![Screenshot2-2021-02-18-at-18 14 05](https://user-images.githubusercontent.com/1836845/108394670-41473f00-7215-11eb-85fb-b62332bc451e.png)

**Comment by enekochan** [comment]
Full error log:

```
No matching member function for call to 'println'

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:79:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:78:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:77:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:80:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:81:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:82:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:83:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:84:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:85:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:86:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:87:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:88:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:89:12:
note: candidate function not viable: no known conversion from 'Uart' to 'arduino::Print' for object argument

/Users/enekochan/Library/Arduino15/packages/arduino/hardware/samd/1.8.11/cores/arduino/api/Print.h:90:12:
note: candidate function not viable: requires 0 arguments, but 1 was provided
```

**Comment by ubidefeo** [comment]
thanks @enekochan 
we'll look for a solution :)
